# Generated by Django 3.1.5 on 2021-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdb',
            name='port',
            field=models.CharField(default='', max_length=10),
        ),
    ]
